### ISSUE TITLE
SystemExit: All your genes ended up in one modules! Reconsider your input parameters in order to get more modules.

### ISSUE THREAD

**Issue by simonekats** [mortazavilab/PyWGCNA#101]
Hi I am trying to run findModules(), but I keep getting this error. Have tried to change parameters with 

pyWGCNA_adata.findModules(kwargs_function={'cutreeHybrid': {'deepSplit': 0, 'pamRespectsDendro': True}}) ...

but still no luck. Any advice?

**Comment by nargesr** [comment]
Hi @simonekats,

This is not the actual error! Based on the inputs, all your genes ended up in one module. so you may need to change the input parameters. 

I don't know how you made your pseudobulk matrix but if you did any prior normalization that might also cause this. or if your expression is too low (lower than 1) it might filter out in the preprocessing process.

**Comment by simonekats** [comment]
Hi! How do I change the input parameters?

**Comment by nargesr** [comment]
Hi,

There are multiple input parameters in different steps that you can change. please look at the [API documentation](https://mortazavilab.github.io/PyWGCNA/html/api.html).

If you are also unfamiliar with R reference WGCNA, I also encourage you to look at [this section](https://github.com/mortazavilab/PyWGCNA?tab=readme-ov-file#suggested-reading) to help you understand the method and parameters better.

**Comment by simonekats** [comment]
By input parameters, do you mean the findModules() parameters, I have tried changing those and with no luck. I am unsure what input parameters you refer to

**Comment by nargesr** [comment]
There are multiple input parameters you can change including [initiating the PyWGCNA object ](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=wgcna#PyWGCNA.wgcna.WGCNA) along with preprocessing parameters and all the steps embedded in the findModules().

you may need to look at the plots that were generated (sample_clustering_cleaning, summary_power, and eigenesgenes) and try to tune your parameters based on them.

But if you still ended up getting one module, it might be related to the data you have.
