### ISSUE TITLE
module_trait_relationships_heatmap

### ISSUE THREAD

**Issue by bsb2014** [mortazavilab/PyWGCNA#102]
PyWGCNA will consider each variable as a single bool trait when more than two variables, such as time points (4mon, 8mon, 12mon, 18mon). I am not sure how to interpret the p-value and correlation for the 4mon. Are the correlation and p-value calculated by comparing 4mon [1] vs other time points [0] (e.g. 4mon vs (8mon+12mon+18mon))? Is that a Pearson correlation? Thanks.

**Comment by bsb2014** [comment]
Another Q, how to extract the eigengenes for the correlation? Thanks.

**Comment by nargesr** [comment]
Hi @bsb2014,

Yes! if you pass them as string it would be one variable versus others. and yes it’s a Pearson correlation calculated through `stats.pearsonr`.

self.MEs contains the eigengenes.

**Comment by bsb2014** [comment]
Please tell me how to use self.MEs? Thanks

I did as 

import PyWGCNA
pyWGCNA_test = PyWGCNA.readWGCNA("test.p")
print(pyWGCNA_test.self.MEs)

AttributeError: 'WGCNA' object has no attribute 'self'

**Comment by nargesr** [comment]
`pyWGCNA_test. MEs`
