### ISSUE TITLE
Visualization error 

### ISSUE THREAD

**Issue by gerapskx** [mortazavilab/PyWGCNA#104]
Hi, 

I have some problems with the figures. Every time i try to generate a plot, the numbers (e.g., p-values) are not complete. This occurs not only with this module-trait heatmap, also whith the heatmap of two-objects comparison. Do you have any idea of why this is occurring?

This is an example;
![Screenshot 2024-06-16 185946](https://github.com/mortazavilab/PyWGCNA/assets/139929491/9f504cdc-3e67-4cf5-8c2b-3573d6cea8af)

**Comment by nargesr** [comment]
Hi @gerapskx 

Which version of pyWGCNA are you using? Does this also happen with a provided example?
Also if you saved the plot, would you be able to see the complete plot?

**Comment by gerapskx** [comment]
> Hi @gerapskx
> 
> Which version of pyWGCNA are you using? Does this also happen with a provided example? Also if you saved the plot, would you be able to see the complete plot?

I am using 2.0.4, 
Actually it started to happen recently, (possible three-two weeks ago)
If i save the plot, still shows like my example

**Comment by nargesr** [comment]
hmm...
Do you mean it worked before and suddenly without any changes such as updating packages, you encountered this?

**Comment by gerapskx** [comment]
> hmm... Do you mean it worked before and suddenly without any changes such as updating packages, you encountered this?

Yes.

**Comment by nargesr** [comment]
I'm not sure if that's something related to PyWGCNA and unfortunately, I'm unable to reproduce your error.

one thing to check is to plot it separately with values stored at `AS_OE.moduleTraitCor` and `AS_OE.moduleTraitPvalue` using `sns.heatmap()`.

It might be something related to your Seaborn package or its dependencies. I found [this issue](https://github.com/microsoft/vscode-jupyter/issues/14363) maybe you had the same thing??

**Comment by gerapskx** [comment]
> I'm not sure if that's something related to PyWGCNA and unfortunately, I'm unable to reproduce your error.
> 
> one thing to check is to plot it separately with values stored at `AS_OE.moduleTraitCor` and `AS_OE.moduleTraitPvalue` using `sns.heatmap()`.
> 
> It might be something related to your Seaborn package or its dependencies. I found [this issue](https://github.com/microsoft/vscode-jupyter/issues/14363) maybe you had the same thing??

I just did the same but for the seaborn package, now it is working. Thank you so much!
