### ISSUE TITLE
gene name question

### ISSUE THREAD

**Issue by chulexuexibiedebushihewo** [mortazavilab/PyWGCNA#106]
When I do pyWGCNA analysis, whether the gene columns I just can use ensemble name, can we use gene name like this?
![image](https://github.com/mortazavilab/PyWGCNA/assets/94608750/f82a8b5b-3e8c-4273-ad88-526bfb7aaed3)

**Comment by nargesr** [comment]
Hi @chulexuexibiedebushihewo 

the gene name seems fine to me but I wanted to mention that the column name should be `gene_name`.
