### ISSUE TITLE
Module 'scores' for each sample to each module

### ISSUE THREAD

**Issue by EDENMEIDAN** [mortazavilab/PyWGCNA#110]
Hey! So happy to be working with your package and work on WGCNA  in python!
I wasn't able to find a way to obtain the module 'scores' for each sample of each module. 

I'm looking for something like this:
         Module1   Module2   ...   ModuleX
Sample1  0.66      0.43      ...   0.33
Sample2  0.45      0.34      ...   0.2

Can you please help me locate this output? 
Thanks, 
Eden

**Comment by nargesr** [comment]
Hi @EDENMEIDAN 

thank you for your sweet comments. 
Could you elaborate a little bit more about what you mean by module 'scores'? What's the equivalent of module 'scores' in the original WGANA?

If you mean module membership, you can use this function called: [CalculateSignedKME()](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=signedkme#PyWGCNA.wgcna.WGCNA.CalculateSignedKME)

**Comment by EDENMEIDAN** [comment]
Yes, I somehow missed this! 
Thank you so much for the quick response :)
