### ISSUE TITLE
Error in documentation and in cutreeHybrid

### ISSUE THREAD

**Issue by Buiboni** [mortazavilab/PyWGCNA#112]
Hi,
thank you for your package!
I tried to use it but I came across several issues:
**in the documentation**: the WGCNA object is said to be initialized with geneExp as:
 _geneExp (pandas dataframe) – expression matrix which genes are in the rows and samples are columns_
however most of the functions use the data as _data – expression data in a matrix or data frame. Rows correspond to samples and columns to genes._, and in the code `findModules()` the data is passed as `self.datExpr.to_df()`. I guess the documentation of WGCNA is wrong since even in your tutorial the columns are genes, and the rows are samples.
**in the code**: in the function `cutreeHybbrid()` line 1752
 `InCluster = list(range(nPoints))[SmallLabels == sclust]` raise an error. I think it is because a list cannot be indexed by something else than an int. However I don't really understand that line so I couldn't try and fix it... If `InCluster` is a list of boolean representing if the gene is in the cluster or not then shouldnt 'SmallLabels == sclust' be enought? When I try to do so, I got an error line 1761...

On an other note, do you plan to add other types of correlation?

Again thank you for your work!

**Comment by nargesr** [comment]
Hi @Buiboni 

in your first question regarding the documentation, I will fix the API documentation in the next release. I forgot to fix it while I was fixing the rest of the documentation. Thank you for catching it.

Regarding your second question, could you share with me the whole error and if you made any modifications to the default input? (if you can share with me the script that you used, that would be great)

I don't have any plan to add new stuff to the package besides maintaining it but if you are willing to add new stuff, I'm happy to help you. and merge it into the current package.

Thank you for using PyWGCNA:)

**Comment by Buiboni** [comment]
Here is a script that would produce the error:
`
import pandas as pd
import PyWGCNA
data = pd.read_csv('expressionList.csv',index_col=0)
pyWGCNA_5xFAD = PyWGCNA.WGCNA(name='5xFAD', 
                              species='mus musculus', 
                              geneExp=data.iloc[:,:200], 
                              outputPath='',
                              save=True)
pyWGCNA_5xFAD.preprocess(show=False)
pyWGCNA_5xFAD.findModules({'cutreeHybrid':{'pamRespectsDendro':True, 
                                      'respectSmallClusters':True}})
`

The error you get is:
`File ~/dev/miniconda3/envs/analysis/lib/python3.12/site-packages/PyWGCNA/wgcna.py:1751 in cutreeHybrid 
                  InCluster = list(range(nPoints))[SmallLabels == sclust]
TypeError: only integer scalar arrays can be converted to a scalar index
`
I am working on a patch to add Spearman correlation. I will let you know when it is done!

**Comment by nargesr** [comment]
Hi @Buiboni ,

I just wanted to let you know that I fixed the error you got.

Do you still have a plan to add Spearman correlation? Just wanted to check with you to see if I need to close this issue or not.

**Comment by Buiboni** [comment]
Hi,
I am still working on that. I will propose a pull request soon!
Did you check the issue  in WGCNA.checkSimilarity(adjMat, min, max)
```pyhon
wgcna.py:983,
    980 if dim[0] != dim[1]:
    981     sys.exit("adjacency is not square")
--> 983 if all(np.max(np.abs(adjMat - adjMat.transpose())) > 1e-12):
    984     sys.exit("adjacency is not symmetric")
    986 if all(np.min(adjMat) < min) or all(np.max(adjMat) > max):

TypeError: 'bool' object is not iterable```

**Comment by nargesr** [comment]
Hi,

Great!

Can you share more details about the error you got? Did you previously open an issue for this one?

I believe I fixed the issue you mentioned in this issue in the beginning and also [this issue](https://github.com/mortazavilab/PyWGCNA/issues/120) related to `checkSimilarity()` function.

If this is something else please provide more information. Thanks!

**Comment by Buiboni** [comment]
This seems to be in the next lines. I don't remember how I got this error, but if I try in a console to do `all(np.max(...)>x)` it will throw an error : `TypeError: 'numpy.bool_' object is not iterable`.
`np.max` or `np.min` seems to return one numeric, so there is no need for `all(..)`.

**Comment by nargesr** [comment]
Hi @Buiboni 

Hope you are doing well. 

Just wanted to let you know that I revisited and fixed all the conditions I have in the `checkSimilarity()` function. Thanks again for catching these.

Please do not hesitate to reopen this issue or open a new one if you encounter any other error(s).

I'm also looking forward to your pull request to add a Spearman correlation. Thanks again for using PyWGCNA and adding more features to it.

Best,
Narges
