### ISSUE TITLE
updateSampleInfo not loading files correctly - can't updateGeneInfo

### ISSUE THREAD

**Issue by franjmt** [mortazavilab/PyWGCNA#116]
Hi! 
I am trying to see if I can analyze proteomics data. I am having problems updating the pyWGCNA sample info.
I load the sample info, but the structure of pyWGCNA.datExpr.obs is different than the one you get from the tutorial:

![image](https://github.com/user-attachments/assets/34694065-f79e-4b44-874d-d53aae0f0881)

![image](https://github.com/user-attachments/assets/c57bdfb1-771e-4d37-869c-453183f649e6)

the sample_id is loading incorrectly.

Then, I am updating the GeneInfo by first getting my gene list as followed:

`geneList = PyWGCNA.getGeneList(dataset='hsapiens_gene_ensembl',
                               attributes=['uniprotswissprot', 
                                           'external_gene_name', 
                                           'gene_biotype'],
                               maps=['prot_name', 'gene_name', 'gene_biotype'])`

I can see a geneList similarly to that from the tutorial, but pyWGCNA.updateGeneInfo(geneList) has an indexing error.

![image](https://github.com/user-attachments/assets/f0425070-e199-44ad-a4ce-339fc2bfcf39)

Do you think this is an issue getting the gene list from BioMart?
Hopefully you can help me!
Thank you

**Comment by nargesr** [comment]
Hi @franjmt 

I would assume if you request the same thing directly from [ensemble website](https://www.ensembl.org/biomart/martview/), you probably get the same table. 

My other assumption is that if you change the order of the `attributes`, will it affect the output? maybe the values of other columns with the same index are different...

I could add a line of code at the end to basically unique the indexes but I prefer to keep the raw input from the ensemble website and the user will be responsible for making sure to pass the write input to the `updateGeneInfo()` function.
