### ISSUE TITLE
Cannot save WGCNA object

### ISSUE THREAD

**Issue by victorsanchezarevalo** [mortazavilab/PyWGCNA#124]
>>> wgcna.saveWGCNA()
Saving WGCNA as WGCNA.p
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
Cell In[10], line 1
----> 1 wgcna.saveWGCNA()
Hide Traceback
File [~/miniconda3/envs/pywgcna/lib/python3.10/site-packages/PyWGCNA/wgcna.py:2754](vscode-file://vscode-app/usr/share/positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#), in WGCNA.saveWGCNA(self)
   2749 """
   2750 Saves the current WGCNA in pickle format with the .p extension
   2751 """
   2752 print(f"{BOLD}{OKBLUE}Saving WGCNA as {self.name}.p{ENDC}")
-> 2754 picklefile = open(self.outputPath + self.name + '.p', 'wb')
   2755 pickle.dump(self, picklefile)
   2756 picklefile.close()

**Comment by nargesr** [comment]
can you tell me if you modify the `outputPath` at any point or not?

what is the type of `outputPath` and `name`?

I believe you'll need to convert the `outputPath` that you used to a string before you save the object. 

I may be able to fix it for the next release as well so it doesn't need to be string but I wanted to make sure that causes the error before making any changes

**Comment by victorsanchezarevalo** [comment]
Hi,

In the script that I have sent you it is defined the outputPath, let me now if you see any mistake, please. 

Best

Victor
