### ISSUE TITLE
TypeError: enrichr() got an unexpected keyword argument 'description'

### ISSUE THREAD

**Issue by tyaoi** [mortazavilab/PyWGCNA#15]
Hi ! 
Thank you for developing PyWGCNA !
Running the command pyWGCNA_5xFAD.analyseWGCNA(geneList=geneList) in the Quick start notebook, I get the following error.

> TypeError: enrichr() got an unexpected keyword argument 'description'

So, I checked the source code in the file PyWGCNA-main/PyWGCNA/wgcna.py, and I found that the above argument is used at the method gp.enrichr() in line3019.

However, in reading the official GSEApy web documentation, I could not find "description='' as an optional argument to the gp.enrichr() method. In my environment, gseapy==0.14.0 is installed through pypi. 

Do I need to install another version of gseapy to solve this problem? Or do I just modify PyWGCNA.py? Which is better? Also, if I modify PyWGCNA.py, how should I install it?

Lastly... it's much easier to use than the R version of WGCNA, and I'm impressed!

Sincerely,

**Comment by tyaoi** [comment]
After modifying wgcna.py as above, I can install it according to the description "Install with the most recent commits"?

**Comment by tyaoi** [comment]
This approach wasn't able to dissolve  the problem.

**Comment by nargesr** [comment]
Hi,

I Gald you liked it!

The version of gseapy I have is 0.10.5 but I'm working on a new release! hopefully, it will be out by mid of next week and I will address this problem! Thanks for letting me know

**Comment by tyaoi** [comment]
Hi !
Thank you for your response.

Looking forward to your new release! 
There are a lot of Python users in this field, so I know lots of people will like it!
