### ISSUE TITLE
Error in .findModules()

### ISSUE THREAD

**Issue by alberto-mora** [mortazavilab/PyWGCNA#16]
After executing the preprocess() function without any problem, in the next step in .findModules(), specifically during the step "Going through the merge tree..." I get an index error:
IndexError: index 67 is out of bounds for axis 0 with size 67
What could be the error?
Thanks in advance!

**Comment by nargesr** [comment]
Hi,

Can you send me an example of your data?

**Comment by alberto-mora** [comment]
![df](https://user-images.githubusercontent.com/93321008/201061568-8e6e3f61-672b-4127-bc5b-9ef560c7eca2.png)

**Comment by nargesr** [comment]
Thank you! Can you also send me the script you used and your PyWGCNA object? you can email me: nargesr@uci.edu

**Comment by alberto-mora** [comment]
Any news?

**Comment by nargesr** [comment]
Hi sorry for the late response. I was working on adding new analysis along with solving this issue. I'll push new changes by end of this week which will resolve this issue as well

again sorry for waiting on this for too long

**Comment by nargesr** [comment]
Hi,

The new release should be fine. I was able to run "findModules()" without any problem.
