### ISSUE TITLE
Import issue on Windows with ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by MysoreSparrow** [mortazavilab/PyWGCNA#20]
Hi,

I am trying to run the code on my windows computer and I frequently run into this windows-specific error : 
` import PyWGCNA` and it results in ModuleNotFoundError: No module named 'resource' . I tried different solutions on Windows but didnt yield anything useful so far. 

I suggest that initial tutorial could be expanded to include imports, and also example(s) for creating anndata object(s) would be very useful indeed. Thank you.

**Comment by q923397935** [comment]
In the PyWGCNA folder, just change the **import reources** in the wgcna script to **import rsrc**，can run in windows

**Comment by MysoreSparrow** [comment]
Thank you for your comment. That was useful. Also, for anyone else who might encounter this issue in future, I did a couple of other thigs as well : Firstly, I installed "rsrc" into my conda env via " pip install rsrc" from https://pypi.org/project/rsrc/ .  Secondly, in the said wgcna.py file, I replaced all the calls of resource with rsrc. Now the import PyWGCNA worked without any issues.

**Comment by q923397935** [comment]
You are welcome. I have also been using the PyWGCNA package to do generic analysis recently and encountered the same problem, which was solved fortunately.




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Keshava Prasad ***@***.***&gt;;
Send time:&nbsp;Monday, Jan 9, 2023 6:31 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [mortazavilab/PyWGCNA] Import issue on Windows with ModuleNotFoundError: No module named 'resource' (Issue #20)





 
Thank you for your comment. That was useful. Also, for anyone else who might encounter this issue in future, I did a couple of other thigs as well : Firstly, I installed "rsrc" into my conda env via " pip install rsrc" from https://pypi.org/project/rsrc/ .  Secondly, in the said wgcna.py file, I replaced all the calls of resource with rsrc. Now the import PyWGCNA worked without any issues.
