### ISSUE TITLE
Errors:IndexError: positional indexers are out-of-bounds

### ISSUE THREAD

**Issue by vvvcgx** [mortazavilab/PyWGCNA#22]
When we performed the function “.findModules”, Python reported an error as“ positional indexes are out of bounds”. Could you please tell us why this happened and what should we do to fix the problem?

![error](https://user-images.githubusercontent.com/98447110/220289230-159819b4-09ad-40d3-89fd-42141b622582.JPG)

**Comment by leohog** [comment]
I'm experiencing the same problem, did you find a solution @vvvcgx ?

**Comment by nargesr** [comment]
Hi,

Thank you for reporting this.
Can both of you send me your input matrix or your PyWGCNA object?
nargesr@uci.edu

**Comment by vvvcgx** [comment]
Dear xx,

Thank you for your kind reply! When we performed the function “.findModules”, Python reported an error as“ positional indexes are out of bounds”、“UnboundLocalError: local variable 'merge' referenced before assignment”. Could you please tell us why this happened and what should we do to fix the problem? I have attached relevant data and codes to this email. Please do not hesitate to contact me if there is any need. I am looking forward to your reply!

Very best regards,

Chen

Message ID: ***@***.***>

从网易126邮箱发来的超大附件推荐客户端极速下载
high.csv (22.48M, 2023年3月9日 15:07 到期)
下载
low.csv (21.24M, 2023年3月9日 15:07 到期)
下载

**Comment by nargesr** [comment]
Hi @leohog,

please install the latest version(1.16.5) it should be fixed. I also ran your data and it was fine

**Comment by nargesr** [comment]
Hi @vvvcgx,

I couldn't see your attached file but since you got the same error as @leohog got, I assume the latest version (1.16.5) will fix your problem, if not please reopen this issue
