### ISSUE TITLE
pyWGCNA maintenance

### ISSUE THREAD

**Issue by wangjiawen2013** [mortazavilab/PyWGCNA#24]
Hi, 
There is a lack of WGCNA in python ecosystem, So we're very glad to see the emergence of pyWGCNA ! However, we still have some worries.
1, I have read the paper "Systematic phenotyping and characterization of the 5xFAD mouse model of Alzheimer’s disease" cited in pyWGCNA preprint. It was said that "We applied PyWGCNA to 192 bulk RNA-seq samples of cortex and hippocampus of the 5xFAD mouse model and matching C57BL6/J mice at 4 ages (4, 8, 12, and 18 months) in both sexes" in pyWGCNA preprint, while I didn't find pyWGCNA (it's WGCNA) in the original 5xFAD paper. So was pyWGCNA or WGCNA used in the paper and what's the relationship between them ?
2, There is a related python packages named iterative WGCNA (https://github.com/cstoeckert/iterativeWGCNA), which is on bioRxiv for many years and not peer reviewed.  I suspect it's not being supported.  Do you known the features of iternative WGCNA and plan to support pyWGCNA for a long time ? We are expecting a python version WGCNA and want to learn how to use pyWGCNA. This will take our a great effect to migrate to pyWGCNA, So we hope it will be supported and stable.

**Comment by nargesr** [comment]
Hi,

1. we used the data in the "Systematic phenotyping and characterization of the 5xFAD mouse model of Alzheimer’s disease" paper and show the results in preprint and tutorials. 
Basically, PyWGCNA and WGCNA use the same strategy to find the modules however PyWGCNA has a lot of downstream analysis/visualizations which help users to understand the functionality of each module better.

2. I have never across this package but I will maintain PyWGCNA as long as I can :)
