### ISSUE TITLE
high resolution PyWGCNA_overview.png

### ISSUE THREAD

**Issue by wangjiawen2013** [mortazavilab/PyWGCNA#25]
Hi,
Some letters on PyWGCNA_overview.png are too small to see clearly, would you mind providing higher resolution figures ?

**Comment by nargesr** [comment]
Hi,

I upload the higher resolution [here](https://github.com/mortazavilab/PyWGCNA/blob/main/docs/PyWGCNA_overview.png)!
Don't hesitate to reopen this issue if the quality is not good enough yet!

**Comment by wangjiawen2013** [comment]
Thanks for you reply!
However, there are some flaws on the figure. such as
3) find modules, 4. the bottom of "identify gene moudles" was covered by the plot
4) study modules, 3. module GO term. The points are covered by the legend
5) compare pywgcnas, 1. comparison table. There are red wave lines under some letter.
