### ISSUE TITLE
getModulenames

### ISSUE THREAD

**Issue by wangjiawen2013** [mortazavilab/PyWGCNA#29]
Hi, there is a typo in this function:
   def getModuleName(self):
        """
        get names of modules
        :return: name of modules
        :rtype: ndarray
        """
        return np.unique(self.datExpr.obs['moduleColors']).tolist() (obs should be **_"var"_**)
Besides,
this typo exists in return getmodule functions, not just this one.

**Comment by nargesr** [comment]
Hi,

Thank you for reporting this! It will be fixed by the next release.
