### ISSUE TITLE
moduleEigengenes function error, failure to use hubgenes

### ISSUE THREAD

**Issue by pelmatt** [mortazavilab/PyWGCNA#30]
Error received during findModules call, preprocessing has already been done. I have all settings on default, including hubGenes = True and traperrors = False. I tried changing traperrors to true however this seemed to make things worse.

error:
Calculating 56 module eigengenes in given set...
..principal component calculation for module antiquewhite failed with the following error:
..hub genes will be used instead of principal components.

%tb:
MEList = WGCNA.moduleEigengenes(expr=self.datExpr.to_df(), colors=self.datExpr.var['dynamicColors'])

File ~\anaconda3\lib\site-packages\PyWGCNA\wgcna.py:2036 in moduleEigengenes
sys.exit("Error!")

I will attach the original data file.
[transposed.csv](https://github.com/mortazavilab/PyWGCNA/files/11221399/transposed.csv)

Many thanks in advance.

**Comment by nargesr** [comment]
traperrors is False by default, so you don't need to pass it and we don't have any hubGenes variable for any of the functions so I don't know what that means.

**Comment by pelmatt** [comment]
Apologies, I meant the subHubs variable, which is on True by dedault.

**Comment by nargesr** [comment]
So you don't need to change the default parameter and I was able to run the PyWGCNA without any error with the data you provided me! please make sure you have the last version of the package and you should be fine!
