### ISSUE TITLE
zero variance

### ISSUE THREAD

**Issue by wangjiawen2013** [mortazavilab/PyWGCNA#31]
Hi,
when I ran pyWGCNA.preprocess(), an error occurred:

Pre-processing...
	Detecting genes and samples with too many missing values...

  ..Excluding 9 genes from the calculation due to too many missing samples or zero variance.

ValueError: operands could not be broadcast together with shapes (3407,) (3398,)

Could you check the code make sure was it caused by zero variance genes ?

**Comment by nargesr** [comment]
Hi,

would you mind sharing your input with me?

**Comment by wangjiawen2013** [comment]
This is a private dataset, but I will send you a public one if I meet the error again.

**Comment by nargesr** [comment]
you can change the column name and row name and send me the subset of your data that contains those 9 genes with zero variance

**Comment by wangjiawen2013** [comment]
I cannot reproduce the error now, I'll send it to you when I meet it again!

**Comment by nargesr** [comment]
I'll close this issue then :)
please reopen this issue if you face the same problem! thank you
