### ISSUE TITLE
module number

### ISSUE THREAD

**Issue by wangjiawen2013** [mortazavilab/PyWGCNA#32]
Hi,
PyWGCNA can determine the module numbers automatically now, how to adjust the number if I wanna increase or decrease the modules ?

**Comment by nargesr** [comment]
Hi,

Every parameter has a default value similar to the original WGCNA. you can change them to what suits you!

for example, one of the parameters related to the number of modules is MEDissThres. right now the default is 0.2, so if you want more modules, you can increase this number.
