### ISSUE TITLE
AttributeError: 'WGCNA' object has no attribute 'top_n_hub_genes'

### ISSUE THREAD

**Issue by anna4kaa** [mortazavilab/PyWGCNA#37]
Hi!

First of all, thank you so much for this package! It has helped me a lot in my data analysis.

I have determined the different modules and now I would like to find the most important hub genes.

However when I run:
**pyWGCNA_NBC.top_n_hub_genes(moduleName="lime", n=10)**

I get error: 
**AttributeError: 'WGCNA' object has no attribute 'top_n_hub_genes'**

I also looked into the source file and it seems like I cannot find the function.
Could you please help me with this?

**Comment by anna4kaa** [comment]
I found the code for the function here and copied into my source file, so it works now. 

https://mortazavilab.github.io/PyWGCNA/html/_modules/PyWGCNA/wgcna.html#WGCNA.CoexpressionModulePlot

Not sure if I personally installed it somehow excluding this part or it is not included in the source code by default.

**Comment by nargesr** [comment]
Hi,

First thank you for your kind comments. I'm glad you found it useful :)
Which version of PyWGCNA, did you use? I added this function recently. so you probably need to update the package

**Comment by anna4kaa** [comment]
I see that I have version 1.16.8. 

It makes sense that It could be that I did not use the newest version, thanks :)
