### ISSUE TITLE
cannot preprocess / manipulate Anndata object

### ISSUE THREAD

**Issue by milanborchert** [mortazavilab/PyWGCNA#38]
Hello,

I have managed to import my count table, annotation and metadata and combined it into an Anndata object, named "Nc_coexp".
To potentially verifiy the structure of the object here the output ftom head command:

Nc_coexp.geneExpr.to_df().head(5)
Out[54]: 
            NCU00003-t26_1  NCU00004-t26_1  ...  NCU17284-t26_1  NCU17285-t26_1
sample_id                                   ...                                
ERR6120389         7.05213         20.6476  ...        0.574325         3.15034
ERR6120390         7.12926         19.5792  ...        0.741205         6.68712
ERR6120391         9.01246         33.8402  ...        0.826182         1.60666
ERR6120392        22.02220         57.4943  ...        3.428080         9.33067
ERR6120393        23.10760         50.7808  ...        2.335950        10.58590

[5 rows x 10813 columns]

as I understand it, Nc_coexp.geneExpr only looks at the count table, which I also want to target for preprocessing. However this does not work:

Nc_coexp.geneExpr.preprocess()
Traceback (most recent call last):

  Cell In[55], line 1
    Nc_coexp.geneExpr.preprocess()

AttributeError: 'AnnData' object has no attribute 'preprocess'

Any idea what I am doing wrong here? it seems like some of the pyWGCNA functions are correctly implemented (like PyWGCNA.geneExp.GeneExp() which allowed me to create the AnnData object in the first place. Preprocess on the other hand does not appear among the listed options when entering "Nc_coexp." and waiting for IDE suggestions.

**Comment by nargesr** [comment]
Hi,

you should pass PyWGCNA object for preprocessing function rather than geneExpr so it should be Nc_coexp.preprocess()

I would recommend looking at the [Quick_Start](https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/Quick_Start.ipynb) tutorial

**Comment by milanborchert** [comment]
Hello, I also tried this and of course read the tutorial. However this leads to a very similar error message:

Nc_coexp.preprocess()
Traceback (most recent call last):

  Cell In[5], line 1
    Nc_coexp.preprocess()

AttributeError: 'GeneExp' object has no attribute 'preprocess'

I created the PyWGCNA object with the following command:

Nc_coexp = PyWGCNA.geneExp.GeneExp(species = "Neurospora_crassa",
                        level = "gene",
                        anndata = None,
                        geneExp = geneExpdf,
                        geneInfo = geneInfodf_sort,
                        sampleInfo = sampleInfodf_sort)

Where geneExp, geneInfo and sampleInfo are taken from dataframes. So while it seemed to run through nicely and can be queried by "Nc_coexp.geneExpr.to_df().head(5)" as shown above, maybe my error is here. 

Since I do not have an already existing PyWGCNA object like in the tutorial I could not fully recreate the tutorial steps and instead checked the usage parameters, where I found the PyWGCNA.geneExp.GeneExp() command. Any further help would be greatly appreciated. If needed I could of course also supply my full code and potentially the input files (or a screenshot of their structure).

**Comment by nargesr** [comment]
you should make your PyWGCNA objects by using `PyWGCNA.WGCNA()` function but instead of passing the gene expression matrix you can pass your anndata object

it should be something like this

`PyWGCNA.WGCNA(name='5xFAD', 
                              species='mus musculus', 
                              anndata=anndata, 
                              outputPath='',
                              save=True)`

for more information, you can look at the [API documentation](https://mortazavilab.github.io/PyWGCNA/html/api.html)
