### ISSUE TITLE
When TOMtype is set to unsigned, an unexpected error will be triggered.

### ISSUE THREAD

**Issue by liuzj039** [mortazavilab/PyWGCNA#42]
Thank you very much to the developers for being willing to develop PyWGCNA

Recently, I found that when TOMtype is set to unsigned, the following error will be triggered: "`TOMType' cannot be 'none' for this function". 

This is probably because when TOMtype is set, TOMTypeC is set to 0 based on [here](https://github.com/mortazavilab/PyWGCNA/blob/2f9d9a7fd88dac719988fa3dd9ebbb0518c84798/PyWGCNA/wgcna.py#LL1115C28-L1115C28), which triggers this error.

In addition, TOMTypeC should not be assigned a value of 2, and it is unclear whether this is expected [here](https://github.com/mortazavilab/PyWGCNA/blob/2f9d9a7fd88dac719988fa3dd9ebbb0518c84798/PyWGCNA/wgcna.py#LL1125C17-L1125C17).

**Comment by nargesr** [comment]
Hi,

Thank you so much for your kind comments :)

You're right! I'll fix this in the next release
Thank you so much for catching that
