### ISSUE TITLE
pyWGCNA.findModules()—— sys.exit("Error!") 

### ISSUE THREAD

**Issue by anna4kaa** [mortazavilab/PyWGCNA#45]
Hi!

I have been using PyWGCNA for a while. Thank you a lot, it has been very useful and did not encounter any errors before.

Recently, I got a new computer so had to re-install everything (I used to have 1.16.8 version of PyWGCNA before). 
I saw that this issue appeared before and also tried versions - 1.2.4 and 1.2.3 (as you suggested to try the newest versions) but still got the same error. I also tried 1.16.8 which used to work before, and the error was still there. My colleague encountered the same error even with the dataset that was provided in the tutorial. 

I checked the requirements and re-installed PyWGCNA several times.

Currently, I am trying to run .findModules() and this is the error I encountered:
-------------------------------------------------------------------------------------------------------------------------------------
Selected power to have scale free network is 9.
calculating adjacency matrix ...
	Done..

calculating TOM similarity matrix ...
	Done..

Going through the merge tree...
..cutHeight not given, setting it to 0.994  ===>  99% of the (truncated) height range in dendro.
	Done..

Calculating 45 module eigengenes in given set...
 ..principal component calculation for module antiquewhite failed with the following error:
     ..hub genes will be used instead of principal components.
An exception has occurred, use %tb to see the full traceback.

SystemExit: Error!

-------------------------------------------------------------------------------------------------------------

I was also running it on a dataset where I did not encounter the error before I re-installed PyWGCNA, so I do not think it is the problem. I have attached it just in case (a final transposed version):  

[https://fromsmash.com/rnaseqdata](url)

I am really running out of ideas of what could be the problem so help would be really appreciated.

**Comment by nargesr** [comment]
Hi,

Can you tell me the version of other packages that are required for PyWGCNA? I uploaded mine [here](https://github.com/mortazavilab/PyWGCNA/blob/main/requirements.txt).

It might be that the new version of numpy is not compatible with the version of numba you have. 

if you can also send me the full traceback of your error that would be great as well.

**Comment by anna4kaa** [comment]
Thank you so much for your advice! Apparently, I had a new version of pandas and when I installed version 1.4.4, It worked, 


The full traceback was this: 

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 pyWGCNA_NBC.findModules()

File ~\AppData\Local\anaconda3\envs\wgcna\lib\site-packages\PyWGCNA\wgcna.py:300, in WGCNA.findModules(self, **kwargs)
    297 self.datExpr.var['dynamicColors'] = WGCNA.labels2colors(labels=dynamicMods)
    299 # Calculate eigengenes
--> 300 MEList = WGCNA.moduleEigengenes(expr=self.datExpr.to_df(), colors=self.datExpr.var['dynamicColors'])
    302 self.MEs = MEList['eigengenes']
    303 if 'MEgrey' in self.MEs.columns:

File ~\AppData\Local\anaconda3\envs\wgcna\lib\site-packages\PyWGCNA\wgcna.py:2009, in WGCNA.moduleEigengenes(expr, colors, impute, nPC, align, excludeGrey, grey, subHubs, softPower, scaleVar, trapErrors)
   2007 if not check:
   2008     if not trapErrors:
-> 2009         sys.exit("Error!")
   2010     print(" ..ME calculation of module", modulename, "failed with the following error:", flush=True)
   2011     print("     ", pc, " ..the offending module has been removed.", flush=True)

SystemExit: Error!
