### ISSUE TITLE
'WGCNA' object has no attribute 'top_n_hub_genes'

### ISSUE THREAD

**Issue by jiansongatnih** [mortazavilab/PyWGCNA#47]
import PyWGCNA
pyWGCNA_5xFAD = PyWGCNA.readWGCNA("5xFAD.p")
pyWGCNA_5xFAD.top_n_hub_genes(moduleName="coral", n=10)

AttributeError: 'WGCNA' object has no attribute 'top_n_hub_genes'

**Comment by nargesr** [comment]
Hi, 

I'm not sure which version of the pickle file and pyWGCNA you have.

please try to install the latest version of PyWGCNA (1.2.4) and download the latest version of the pickle file (V3).
Hopefully, that solves your problems.

**Comment by jiansongatnih** [comment]
Thank you Narges! Installing the latest version of PyWGCNA (1.2.4) resolved the problem.
