### ISSUE TITLE
Error with findModules()

### ISSUE THREAD

**Issue by FeedFall8** [mortazavilab/PyWGCNA#49]
Hello, I am trying to begin using WGCNA for a project of ours.
When I attempt to load the modules for the PyWGCNA object I receive an error when eigengenes  are being calculated.
![image](https://github.com/mortazavilab/PyWGCNA/assets/58020585/68e8a77c-d311-402e-b15b-dd85e80f717d)

```python
import PyWGCNA, os
import numpy as np
import pandas as pd

PATH_1 = "datasets/Heart_Left_Ventricle.v8.normalized_expression.bed"
PATH_2 = "datasets/gene_tpm_heart_left_ventricle.gct"
PATH_3 = "datasets/expressionList.csv"
# Assuming `fulldata` is your DataFrame and it has been loaded correctly
fulldata = pd.read_csv(PATH_1, sep='\t', header=0)

fulldata_2 = pd.read_csv(PATH_2, sep='\t', header=0)

# fulldata_3 = pd.read_csv(PATH_3, header=0)


# Transpose the dataframe and select columns
datExpr0 = fulldata.iloc[:, 4:390].T  # Python uses 0-based indexing
datExpr1 = fulldata_2.iloc[:, 3:389].T  # Python uses 0-based indexing
# Set column names to gene_id
datExpr0.columns = fulldata['gene_id'].values
datExpr1.columns = fulldata_2['Name'].values


# Set row names (index)
datExpr0.index = fulldata.columns[4:390]
print(datExpr0.index.str.replace("-", ""))
datExpr1.index = fulldata_2.columns[3:389]

datExpr0.index=datExpr0.index.str.replace("-", "")
datExpr1.index=datExpr0.index.str.replace("-", "")
# View the dataframe
print("#1", datExpr0)
print("#2", datExpr1)
# print("#3", fulldata_3)
gsg = PyWGCNA.WGCNA.goodSamplesGenes(datExpr0)

allOK = gsg[-1]
print(allOK)
if not allOK:
    # Optionally, print the gene and sample names that were removed
    if sum(not gsg[1]) > 0:
        print("Removing genes:", ", ".join(list(datExpr0.columns[~gsg[1]])))
    if sum(not gsg[0]) > 0:
        print("Removing samples:", ", ".join(list(datExpr0.index[~gsg[0]])))

    # Remove the offending genes and samples from the data
    datExpr0 = datExpr0.loc[gsg[0], gsg[1]]
print("PICKING THRESHOLD")

DSet = PyWGCNA.WGCNA(name='GTEX-111FC',
                     species='Humans',
                     geneExp=datExpr0,
                     outputPath=os.path.realpath(''),
                     TOMType='unsigned',
                     powers=[10],
                     # sft=sfT,
                     # cut=2,
                     networkType="unsigned",
                     save=True)

DSet2 = PyWGCNA.WGCNA(name='GTEX',
                      species='Humans',
                      geneExp=datExpr1,
                      outputPath=os.path.realpath(''),
                      TOMType='unsigned',
                      powers=[10],
                      # sft=sfT,
                      # cut=2,
                      networkType="unsigned",
                      save=True)





print("PREPROCESSING")
DSet.preprocess()
# DSet2.preprocess()
print("FINDING MODULES")
DSet.findModules()
```

This is the dataframe I pass to the PyWGCNA object,  I have to modify it to be in the correct format.

![image](https://github.com/mortazavilab/PyWGCNA/assets/58020585/ebe8ce70-7168-4285-a7de-453cd8b3aae5)

I am running this script on Python 3.7

**Comment by nargesr** [comment]
Hi,

it looks like you do have negative values, right?

also, preprocess() will run goodSamplesGenes(), why did you run it before you pass your matrix?

**Comment by FeedFall8** [comment]
Hello, thank you for responding.

The goodSamplesGenes() was a oversight from an earlier test.
What do you advise for the script? Is the negative values the cause?

**Comment by nargesr** [comment]
it might be but I'm not sure ...
can you send me a subset of your data that will give you the same error?
you can change the row and column names of your data with something else if your data is not publicly available

**Comment by FeedFall8** [comment]
[data_heart_left_ventricle_sample.csv](https://github.com/mortazavilab/PyWGCNA/files/11853962/data_heart_left_ventricle_sample.csv)

Here is a subset of the dataset I am using, it is from https://gtexportal.org/home/datasets

**Comment by nargesr** [comment]
I was able to run PyWGCNA on the dataset you provided!
I would suggest check the version of all your all the other packages which I listed mine [here](https://github.com/mortazavilab/PyWGCNA/blob/main/requirements.txt)
also the python version I have is 3.10.4

I also put my script bellow just in case
`
import PyWGCNA
import pandas as pd

tpm = pd.read_csv('data_heart_left_ventricle_sample.csv', index_col=0)

test = PyWGCNA.WGCNA(name='GTEX-111FC',
                     species='Humans',
                     geneExp=tpm,
                     TOMType='unsigned',
                     powers=[10],
                     networkType="unsigned",
                     save=True)

test.preprocess()

test.findModules()
`

**Comment by FeedFall8** [comment]
Thank you!
I reinstalled my packages with the same versions as the PyWGCNA requirements and everything runs as intended! 
Before this issue is closed, are there any plans to add support for Cytoscape networks in future versions of PyWGCNA? 
https://manual.cytoscape.org/en/stable/Supported_Network_File_Formats.html

**Comment by nargesr** [comment]
great!

Sorry but for now, I don't have a plan to add support for Cytoscape networks:)
but if you want to give it a shot, you're welcome to do and I will be happy to help you integrate that with PyWGCNA
