### ISSUE TITLE
Input data format different than the tutorial

### ISSUE THREAD

**Issue by NISH1001** [mortazavilab/PyWGCNA#5]
Hi,

In the quickstart tutorial, it's shown that the `geneExp = '5xFAD_paper/expressionList_sorted.csv'` data is loaded to give us this pandas dataframe as:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/4786694/173466399-2764576b-9c59-40a3-9f76-56764af218bb.png">

However, while I downloaded the data and loaded it ditto, I get a transposed version of the same dataframe:
![image](https://user-images.githubusercontent.com/4786694/173466442-503d6882-eb48-447e-a9c9-e8c9b8a877b5.png)

Can you please help me with understanding what the actual format is? In the [Data Input, cleaning and preprocessing](https://mortazavilab.github.io/PyWGCNA/html/tutorials/Data_format.html) doc, it does seem that the dataframe format I get while loading on my side is the correct one.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/4786694/173466538-029c3479-5315-44a9-9b61-6df225379435.png">

Which is the actual format that PyWGCNA works on?

Thanks.

**Comment by nargesr** [comment]
Hi @NISH1001

Thank you for pointing out the differences, I updated the tutorials ([Data input, cleaning and pre-processing](https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/Data_format.md)) and [5xFAD.p](https://zenodo.org/record/6672453#.YrDcwbnMJhF).
