### ISSUE TITLE
server error in getting gene list

### ISSUE THREAD

**Issue by kunalkathuria** [mortazavilab/PyWGCNA#50]
Hello!

I encountered the following error when running 

geneList = PyWGCNA.getGeneList(dataset='mmusculus_gene_ensembl',
                               attributes=['ensembl_gene_id', 
                                           'external_gene_name', 
                                           'gene_biotype'])

Traceback (most recent call last):
  File "/users/kkathuri/nscripts/python/runWGCNA.v2.py", line 55, in <module>
    'gene_biotype'])
  File "/users/kkathuri/.local/lib/python3.7/site-packages/PyWGCNA/utils.py", line 97, in getGeneList
    server = biomart.BiomartServer('http://uswest.ensembl.org/biomart')
  File "/users/kkathuri/.local/lib/python3.7/site-packages/biomart/server.py", line 27, in __init__
    self.assert_alive()
  File "/users/kkathuri/.local/lib/python3.7/site-packages/biomart/server.py", line 48, in assert_alive
    self.get_request()
  File "/users/kkathuri/.local/lib/python3.7/site-packages/biomart/server.py", line 104, in get_request
    r.raise_for_status()
  File "/jhpce/shared/jhpce/core/python/3.7.3/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: http://uswest.ensembl.org/biomart/martservice

Should I just keep trying or is there a different work-around? 

Thank you!

Best,

Kunal

**Comment by nargesr** [comment]
Hi,

I don't think so you have the latest version of the PyWGCNA. it should be fixed in the new version.

Also, keep in mind that this function tries to get the table that map gene ensembl id to gene name using biomart website which might be down sometimes. 
In the new version of package, you can define which domain you want to use. please look at the API documentation for more info.

**Comment by kunalkathuria** [comment]
Oh okay. I cloned the repository perhaps a week or so ago and did a pip install on the directory. Has there been an update subsequently?

**Comment by nargesr** [comment]
which version do you have? the latest one is 1.2.4.

The main reason I believe you don't have the latest version is that the default server domain is [this](https://www.ensembl.org/biomart/martview) but the one shown in your error is [this](http://uswest.ensembl.org/biomart/martservice) which is not available right now as well.

**Comment by kunalkathuria** [comment]
Thank you. I am using 1.2.4 now on Python3.8 and will reopen this if necessary. Appreciate the quick responses.
