### ISSUE TITLE
hub genes will be used instead of principal components error?

### ISSUE THREAD

**Issue by QUEST2179** [mortazavilab/PyWGCNA#56]
pip install PyWGCNA today, then run Quick_Start notebook and got the following error 

Run WGCNA...
pickSoftThreshold: calculating connectivity for given powers...
will use block size  1876
    Power  SFT.R.sq     slope truncated R.sq      mean(k)    median(k)       max(k)
0       1  0.368857 -0.481613       0.701585  2444.750756  2260.416614  5665.102661
1       2    0.7253  -0.99165       0.886361   840.665489   673.081241  3009.058821
2       3  0.791986 -1.194264       0.946969   385.685335   258.451265  1916.810605
3       4  0.835392   -1.3419       0.968446   207.404152   113.456087  1332.762771
4       5  0.853842 -1.472183       0.973346   123.232581    54.784481   984.036824
5       6  0.870673 -1.553348       0.979584    78.455923     28.47124   752.959999
6       7  0.886736 -1.600869       0.986635    52.572016    15.594822   591.514192
7       8  0.896672 -1.639343       0.992373     36.65884     9.454046   475.817182
8       9  0.903531 -1.677747       0.994643    26.397061     6.024431   389.237531
9      10  0.906045 -1.706474       0.995895    19.521431     3.975959   322.823838
10     11  0.905582 -1.731076       0.994806    14.767291     2.623921   270.867416
11     13  0.914482 -1.751347       0.997466     8.941254     1.205108   196.222414
12     15  0.912684 -1.771227       0.994189     5.759987     0.568044   146.575349
13     17  0.912188 -1.774908       0.990829     3.905403     0.273242   112.189052
14     19  0.907649 -1.774186       0.989457     2.766824     0.135454    87.594344
Selected power to have scale free network is 9.
calculating adjacency matrix ...
        Done..

calculating TOM similarity matrix ...
        Done..

Going through the merge tree...
..cutHeight not given, setting it to 0.996  ===>  99% of the (truncated) height range in dendro.
        Done..

Calculating 22 module eigengenes in given set...
 ..principal component calculation for module black failed with the following error:
     ..hub genes will be used instead of principal components.
Error!

**Comment by nargesr** [comment]
please install the latest version which is 1.2.4

**Comment by BFootYU** [comment]
I ran into the same error while not using the latest version of PyWGCNA. But, after I installed the latest one and reran the Quick_Start, a new error popped out before the steps where the previous error occurred. Here is the error message,

```
FileNotFoundError                         Traceback (most recent call last)
Cell In[17], line 1
----> 1 pyWGCNA_5xFAD.preprocess()

File [~/SSD4/tools/miniconda3/envs/WGCNA/lib/python3.9/site-packages/PyWGCNA/wgcna.py:227], in WGCNA.preprocess(self)
    225 plt.tight_layout()
    226 if self.save:
--> 227     plt.savefig(f"{self.outputPath}/figures/sample_clustering_cleaning.{self.figureType}")
    229 # Determine cluster under the line
    230 clust = WGCNA.cutree(sampleTree, cutHeight=self.cut)

File [~/SSD4/tools/miniconda3/envs/WGCNA/lib/python3.9/site-packages/matplotlib/pyplot.py:1023], in savefig(*args, **kwargs)
   1020 @_copy_docstring_and_deprecators(Figure.savefig)
   1021 def savefig(*args, **kwargs):
   1022     fig = gcf()
-> 1023     res = fig.savefig(*args, **kwargs)
   1024     fig.canvas.draw_idle()  # Need this if 'transparent=True', to reset colors.
   1025     return res

File [~/SSD4/tools/miniconda3/envs/WGCNA/lib/python3.9/site-packages/matplotlib/figure.py:3378], in Figure.savefig(self, fname, transparent, **kwargs)
   3374     for ax in self.axes:
   3375         stack.enter_context(
   3376             ax.patch._cm_set(facecolor='none', edgecolor='none'))
-> 3378 self.canvas.print_figure(fname, **kwargs)
...
--> 494         fh = open(fname, flag, encoding=encoding)
    495     opened = True
    496 elif hasattr(fname, 'seek'):

FileNotFoundError: [Errno 2] No such file or directory: '/figures/sample_clustering_cleaning.pdf'
```

**Comment by QUEST2179** [comment]
I got the same error after switching to v1.2.4, similar to what BFootYu user observed.

**Comment by nargesr** [comment]
Hi @BFootYU

That extra "/" shouldn't affect anything, unless you use your own custom output path.

about the other error, both of you faced (@QUEST2179 @BFootYU):
Please look at the[ requirements.txt](https://github.com/mortazavilab/PyWGCNA/blob/main/requirements.txt) and install the same version of the other packages I have.

**Comment by BFootYU** [comment]
Got it, I'll test it without customizing the output path later.

I successfully ran Quick_Start notebook with the same version of the packages recorded in the requirements.txt installed.

After that, I also created a new conda environment, used pip to install PyWGCNA without specifying the version, and then successfully executed the Quick_Start.ipynb just with the pandas package switching from the latest one back to 1.4.4 as suggested in the requirement.txt file.

```
name: WGCNA
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - comm=0.1.3=pyhd8ed1ab_0
  - debugpy=1.6.7=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.24.0=pyh71e2992_0
  - ipython=8.14.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39hf3d152e_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=pyhd8ed1ab_0
  - platformdirs=3.8.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py39h72bdee0_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.9.16=h2782a2a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pyzmq=25.1.0=py39hb257651_0
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.3.2=py39hd1e30aa_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - pip:
      - anndata==0.9.1
      - biomart==0.9.2
      - certifi==2023.5.7
      - charset-normalizer==3.2.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.40.0
      - gseapy==1.0.5
      - h5py==3.9.0
      - idna==3.4
      - importlib-resources==6.0.0
      - jinja2==3.1.2
      - joblib==1.3.1
      - json5==0.9.14
      - jsonpickle==3.0.1
      - kiwisolver==1.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - memoir==0.0.3
      - natsort==8.4.0
      - networkx==3.1
      - numpy==1.23.2
      - pandas==1.4.4
      - patsy==0.5.3
      - pillow==10.0.0
      - pyparsing==3.0.9
      - pytz==2023.3
      - pyvis==0.3.2
      - pywgcna==1.16.8
      - reactome2py==3.0.0
      - reprit==0.9.0
      - requests==2.31.0
      - rsrc==0.1.3
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - seaborn==0.12.2
      - statsmodels==0.14.0
      - threadpoolctl==3.1.0
      - tzdata==2023.3
      - urllib3==2.0.3
prefix: /home/f05b42016/SSD4/tools/miniconda3/envs/WGCNA
```
