### ISSUE TITLE
UnboundLocalError: cannot access local variable 'merge' where it is not associated with a value

### ISSUE THREAD

**Issue by li1553770945** [mortazavilab/PyWGCNA#57]
In wgcna.py line 308, if the shape of `MEDiss` is `(1,1)`, then the variable `merge` will be used before define.
![image](https://github.com/mortazavilab/PyWGCNA/assets/55867654/a4c1cb84-8a07-4cb3-a2bd-bfc187be465f)
![image](https://github.com/mortazavilab/PyWGCNA/assets/55867654/ed00ae5d-d3bc-4a44-8609-99cfd10d70c2)

**Comment by nargesr** [comment]
I believe this means that you probably ended up having one module at the end.
If you want, you can send me your input to check that.

I will fix this error to pop up as a warning in the next release

**Comment by nargesr** [comment]
Hi,

I was able to run PyWGCNA on the dataset you provided!
I would suggest checking the version of all your other packages which I listed mine [here](https://github.com/mortazavilab/PyWGCNA/blob/main/requirements.txt)
also, the Python version I have is 3.10.4

**Comment by li1553770945** [comment]
Thanks for your reply, I will try to run again after changing the python version.
