### ISSUE TITLE
What does this error mean when i run '.findModules()' ?

### ISSUE THREAD

**Issue by chakitarora** [mortazavilab/PyWGCNA#59]
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
Input In [21], in <cell line: 1>()
----> 1 pyWGCNA_5xFAD.findModules()

File ~/.conda/envs/Py3.10/lib/python3.10/site-packages/PyWGCNA/wgcna.py:300, in WGCNA.findModules(self, **kwargs)
    297 self.datExpr.var['dynamicColors'] = WGCNA.labels2colors(labels=dynamicMods)
    299 # Calculate eigengenes
--> 300 MEList = WGCNA.moduleEigengenes(expr=self.datExpr.to_df(), colors=self.datExpr.var['dynamicColors'])
    302 self.MEs = MEList['eigengenes']
    303 if 'MEgrey' in self.MEs.columns:

File ~/.conda/envs/Py3.10/lib/python3.10/site-packages/PyWGCNA/wgcna.py:2036, in WGCNA.moduleEigengenes(expr, colors, impute, nPC, align, excludeGrey, grey, subHubs, softPower, scaleVar, trapErrors)
   2034 if not check:
   2035     if not trapErrors:
-> 2036         sys.exit("Error!")
   2037     print(" ..ME calculation of module", modulename, "failed with the following error:", flush=True)
   2038     print("     ", pc, " ..the offending module has been removed.", flush=True)

SystemExit: Error!

**Comment by chakitarora** [comment]
I am trying the quickstart.ipynb with my dataset

**Comment by chakitarora** [comment]
<img width="888" alt="Screenshot 2023-08-02 at 13 04 19" src="https://github.com/mortazavilab/PyWGCNA/assets/32720238/367503b2-9c7d-43c2-95ad-0a5c99f1517c">

**Comment by nargesr** [comment]
Hi,

As you see in the picture, you ended up with only one module at the end (Calculating 1 module eigengenes)

I will fix this in the next release so instead of throwing an error it's gonna be a warning but in your case, you might need to tune the input parameters a little bit to be able to get more than 1 one module
