### ISSUE TITLE
missing data 3xTgAD_paper

### ISSUE THREAD

**Issue by jumoline** [mortazavilab/PyWGCNA#60]
Hi, 
I'm going thought the tutorial Notebooks, and 3xTgAD_paper shows as one of the datasets to compare against the 5xFAD_paper. Could we please have a link to the data?
Regards
J

**Comment by nargesr** [comment]
Hi,

There are two papers where you can find information and bulk RNA-seq datasets using 3xTgAD mice:
1. https://www.frontiersin.org/articles/10.3389/fnins.2021.785276/full
2. https://www.biorxiv.org/content/10.1101/2021.09.29.462436v1.full

If you need an actual pickle file, please let me know and I can upload it to Zenodo

**Comment by jumoline** [comment]
Thank you, that would be very useful  :)

**Comment by nargesr** [comment]
Sure! I just upload the pickle file [here](https://zenodo.org/record/8067256)

Please let me know if there is any problem

**Comment by jumoline** [comment]
Awesome, thank you very much
