### ISSUE TITLE
Issue with analyseWGCNA

### ISSUE THREAD

**Issue by jumoline** [mortazavilab/PyWGCNA#63]
Hi I'm using human expression (694, 60504)
I'm getting this issue:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_459/790637460.py in <module>
----> 1 pyWGCNA_5xFAD.analyseWGCNA()
      2 #need to mod and get less times and samples

~/.local/lib/python3.8/site-packages/PyWGCNA/wgcna.py in analyseWGCNA(self, order, geneList, show)
    386 
    387         if self.save:
--> 388             self.module_trait_relationships_heatmap(metaData=self.datExpr.obs.columns.tolist(),
    389                                                     show=show,
    390                                                     file_name='module-traitRelationships')

~/.local/lib/python3.8/site-packages/PyWGCNA/wgcna.py in module_trait_relationships_heatmap(self, metaData, show, file_name)
   2761 
   2762         sns.set(font_scale=1.5)
-> 2763         res = sns.heatmap(self.moduleTraitCor.T, annot=labels, fmt="", cmap='RdBu_r',
   2764                           vmin=-1, vmax=1, ax=ax, annot_kws={'size': 20, "weight": "bold"},
   2765                           xticklabels=xlabels, yticklabels=ylabels)

~/.local/lib/python3.8/site-packages/seaborn/_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48 

~/.local/lib/python3.8/site-packages/seaborn/matrix.py in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, xticklabels, yticklabels, mask, ax, **kwargs)
    551     if square:
    552         ax.set_aspect("equal")
--> 553     plotter.plot(ax, cbar_ax, kwargs)
    554     return ax
    555 

~/.local/lib/python3.8/site-packages/seaborn/matrix.py in plot(self, ax, cax, kws)
    334 
    335         # Possibly rotate them if they overlap
--> 336         _draw_figure(ax.figure)
    337 
    338         if axis_ticklabels_overlap(xtl):

~/.local/lib/python3.8/site-packages/seaborn/utils.py in _draw_figure(fig)
     93     """Force draw of a matplotlib figure, accounting for back-compat."""
     94     # See https://github.com/matplotlib/matplotlib/issues/19197 for context
---> 95     fig.canvas.draw()
     96     if fig.stale:
     97         try:

~/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    392     def draw(self):
    393         # docstring inherited
--> 394         self.renderer = self.get_renderer()
    395         self.renderer.clear()
    396         # Acquire a lock on the shared font cache.

~/.local/lib/python3.8/site-packages/matplotlib/_api/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    382             # Early return in the simple, non-deprecated case (much faster than
    383             # calling bind()).
--> 384             return func(*inner_args, **inner_kwargs)
    385         arguments = signature.bind(*inner_args, **inner_kwargs).arguments
    386         if is_varargs and arguments.get(name):

~/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in get_renderer(self, cleared)
    409         reuse_renderer = (self._lastKey == key)
    410         if not reuse_renderer:
--> 411             self.renderer = RendererAgg(w, h, self.figure.dpi)
    412             self._lastKey = key
    413         elif cleared:

~/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in __init__(self, width, height, dpi)
     82         self.width = width
     83         self.height = height
---> 84         self._renderer = _RendererAgg(int(width), int(height), dpi)
     85         self._filter_renderers = []
     86 

ValueError: Image size of 1440x102708 pixels is too large. It must be less than 2^16 in each direction.
Error in callback <function _draw_all_if_interactive at 0x7f703079bdc0> (for post_execute):

**Comment by nargesr** [comment]
Hi,

Thanks for using PyWGCA.

To me, it seems you have too many traits and because of that, it couldn’t render the plot properly! but If you send me your pickle file, I can investigate it more deeply.

one quick way to solve it is by using module_trait_relationships_heatmap() and passing the subset of your trait (metaData)

more information about this function: https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=module_trait_relationships#PyWGCNA.wgcna.WGCNA.module_trait_relationships_heatmap

**Comment by jumoline** [comment]
Thanks, that helped me trace the problem to the first column name. I didn't know that both sample columns have strict naming as "sample_id". I changed both column names, and it works
regards
J
