### ISSUE TITLE
No enrich terms when cutoff = 1 in module black

### ISSUE THREAD

**Issue by DDXRBHCN** [mortazavilab/PyWGCNA#64]
**Firstly, thank the author very much. Here is the code.**

import PyWGCNA

geneExp = "C:\\Users\\18308\\Desktop\\WGCNA\\data\\data.csv"

pyWGCNA_5xFAD = PyWGCNA.WGCNA(name='data',
                              species='mus musculus',
                              geneExpPath=geneExp,
                              outputPath="C:\\Users\\18308\\Desktop\\WGCNA\\data\\1",
                              save=True,
                              TPMcutoff=0.9)
pyWGCNA_5xFAD.geneExpr.to_df().head(5)
pyWGCNA_5xFAD.preprocess()
pyWGCNA_5xFAD.findModules()
pyWGCNA_5xFAD.updateSampleInfo(path="C:\\Users\\18308\\Desktop\\WGCNA\\data\\label1.csv")

# add color for metadata
pyWGCNA_5xFAD.setMetadataColor('label', {'0': 'green',
                                       '1': 'yellow'})

geneList = PyWGCNA.getGeneList(dataset='mmusculus_gene_ensembl',
                               attributes=['ensembl_gene_id',
                                           'external_gene_name',
                                           'gene_biotype'],
                               maps=['gene_id', 'gene_name', 'gene_biotype'])

pyWGCNA_5xFAD.updateGeneInfo(geneList)
pyWGCNA_5xFAD.analyseWGCNA()
pyWGCNA_5xFAD.saveWGCNA()

**When running the above code, the following prompt appears:**
No enrich terms when cutoff = 1 in module black
No enrich terms when cutoff = 1 in module darkgrey
No enrich terms when cutoff = 1 in module darkred
No enrich terms when cutoff = 1 in module darksalmon
No enrich terms when cutoff = 1 in module firebrick
No enrich terms when cutoff = 1 in module indianred
No enrich terms when cutoff = 1 in module lightgrey
No enrich terms when cutoff = 1 in module mistyrose
No enrich terms when cutoff = 1 in module red
No enrich terms when cutoff = 1 in module rosybrown
No enrich terms when cutoff = 1 in module salmon
No enrich terms when cutoff = 1 in module silver
No enrich terms when cutoff = 1 in module whitesmoke

**Why is this? How can I change cutoff?**

**Comment by nargesr** [comment]
Hi,

Thank you for using PyWGCNA.

Would you mind sending me a snapshot of your `pyWGCNA_5xFAD.datExpr.var`? I wanted to make sure you have a correct gene name column in your dataset.

But overall if you have the correct info in your PyWGCNA object that means there are no GO terms (the cutoff is p-value). you can also do GO analysis directly using [functional_enrichment_analysis()](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=functional_enrichment_analysis#PyWGCNA.wgcna.WGCNA.functional_enrichment_analysis).

More information: https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/functional_enrichment_analysis.ipynb
