### ISSUE TITLE
How to change parameter in findModules()???

### ISSUE THREAD

**Issue by ZivTQ** [mortazavilab/PyWGCNA#65]
Hi, 
thanks for your pyWGCNA tools. But I have some problems.
I want to know how to set the parameter in functions?
I did not find in the Tutorials.
Thanks

**Comment by nargesr** [comment]
Hi,

Thank you for using PyWGCNA :)

for more depth in analysis, I would suggest you look at your interesting function in the [API documentation](https://mortazavilab.github.io/PyWGCNA/html/api.html).

I would say, most of the main parameters should be defined when you initiate your WGCNA object. look at [here](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=wgcna#PyWGCNA.wgcna.WGCNA)

But if there are any specific parameters that you are looking for and aren’t able to find in the API documentation, feel free to reopen this issue.

Thanks
