### ISSUE TITLE
How to add color for metadata consisting of continuous variables and plot the module-trait relationship?

### ISSUE THREAD

**Issue by scuhkf** [mortazavilab/PyWGCNA#68]
First，thank you for the author's excellent work. My sample metadata consists of continuous variables, instead of categorical variables as used in the tutorial. I would like to know how to visualize a module-trait relationship heatmap?
I have updated sample information like this：
![image](https://github.com/mortazavilab/PyWGCNA/assets/135029976/b472c631-0ed0-422f-9f88-4d49bfa29e0d)
Then, I don't know how to add color for continuous variables and directly run `object.analyseWGCNA()`.The row labels of the output image are displayed as numbers from the dataframe instead of column names.
![image](https://github.com/mortazavilab/PyWGCNA/assets/135029976/0e9e59bb-57de-4098-aeab-6ee3432e4990)
I would appreciate it if you could point out where my mistake is. Thank you very much!

**Comment by nargesr** [comment]
Hi, Thanks for your kind comment:)

you should be able to find your answer by looking at issue #55 :)

Please don't hesitate to reopen this issue if you still have further questions.
