### ISSUE TITLE
Integer Gene Labels with geneExp.py

### ISSUE THREAD

**Issue by nmank** [mortazavilab/PyWGCNA#7]
Suppose we have integer gene labels, eg. Entrez Identifiers.

On line 63 of geneExp.py you say
    index=expressionList.values[:, 0]

If the first column of expression list (the gene labels) contains all entries of type int, this forces it to be the same type as the rest of the entries in expressionList. Namely, a float or double. This leads to an error in line 69 where you write

    self.geneExpr = ad.AnnData(X=expressionList, obs=sampleInfo, var=geneInfo)

A fix for this is to write np.array(expressionList.iloc[:,0]) instead of expressionList.values[:, 0] on line 63.

**Comment by nargesr** [comment]
I did not think about that and thank you for pointing that out. I pushed a new release. You can reinstall it from pip. It should be fixed.
