### ISSUE TITLE
Different results generated by v1.15 and v1.20

### ISSUE THREAD

**Issue by hanbinlu** [mortazavilab/PyWGCNA#74]
Hi,

Thank you for creating and maintaining this great package.

I recently upgraded pywgcna from 1.15.0 to 1.20.3, however, I got different results analyzing the same data. Version 1.15.0 resolved 50 modules and v1.20.3 67 modules. Do you have any insights on what factors causing the changes?

This is the code I ran:
```
wgcna_obj = PyWGCNA.WGCNA(
        name="rna_scaled",
        geneExp=geneExp,
        minModuleSize=50,
    )
wgcna_obj.findModules()
```

Thank you very much for your help,
Hanbin

**Comment by nargesr** [comment]
Hi,

Thank you for your kind comments :)

there was a minor issue when I assigned modules to genes. it didn’t change stuff much in my test data so I didn’t think it should be making that huge changes.

One thing I would do is compare these PyWGCNA objects using [Compare two PyWGCNA objects](tutorials/Comparison_two_PyWGCNAs.ipynb), so it will give you some insight into how the modules change
