### ISSUE TITLE
Unable to run the package due to pandas issue. I am attaching the screenshot for the error generated. 

### ISSUE THREAD

**Issue by tanush84** [mortazavilab/PyWGCNA#79]
![Screenshot from 2023-12-05 11-51-51](https://github.com/mortazavilab/PyWGCNA/assets/12098453/cec293bc-8922-40a6-8ed4-cf6a1930b211)

**Comment by nargesr** [comment]
Hi,

did you try installing pandas separately? 
Were you able to install PyWGCNA without any errors?

**Comment by tanush84** [comment]
Dear Author
I tried install version 1.4.4, 1.5.3, 2.1.0 seperately without any success.
The PyWGCNA installation does not throw any error. Currently, I am trying to install all requirements seperately. 
Will update if it works.

**Comment by tanush84** [comment]
Dear Author
I think the Python version 3.10.13 does not have any issue with installing pandas version 2.1.1. May be a bug with other python version. It would be helpful if compiling the requirements with python version 3.10.13. I have not tried other higher versions but hopefully they will work. 
regards
Tanuj

**Comment by nargesr** [comment]
Hi @tanush84 ,

Sorry, I couldn’t catch the problem here. 
were you able to execute `pip install PyWGCNA -U` without any error? if yes which version of pandas were installed along with PyWGCNA?

**Comment by tanush84** [comment]
Hello @nargesr ,
Yes I was able to install the PyWGCNA without any error. It worked by initially created conda environment using python version 3.10.13. 
Then I installed pandas version 2.1.1 using conda install -c conda-forge pandas==2.1.0.
Then I install PyWGCNA using Pip 
pip install PyWGCNA

**Comment by nargesr** [comment]
Hi,

and you couldn’t import pyWGCNA and pandas packages in your notebook?
I feel like that is your conda environment. I tried to install PyWGCNA using Python 3.9/10/11 and everything was fine
