### ISSUE TITLE
outputPath does not work

### ISSUE THREAD

**Issue by DJSiddharthVader** [mortazavilab/PyWGCNA#8]
When creating a WGCNA object I cannot set the outputPath argument and always receive and error i.e.
```
data = PyWGCNA.WGCNA(anndata=counts, save=True, outputPath='./figures')
Traceback (most recent call last):
  File "pywgcna_test.py", line 21, in <module>
    minModuleSize=30,
  File "/PHShome/sr1068/.conda/envs/pywgcna/lib/python3.7/site-packages/PyWGCNA/wgcna.py", line 173, in __init__
    if not os.path.exists(self.outputPath + '/figures/'):
AttributeError: 'WGCNA' object has no attribute 'outputPath'

```
 I looked at the code and in the WGCNA class the variable is never instantiated, adding the line
```
self.outputPath = outputPath
```
to the WGCNA class in `wgcna.py` fixed this issue and allows me to set outputPath.

**Comment by nargesr** [comment]
I'm so sorry, this line totally looks like I edited it in internal testing and somehow I forgot to add it. I pushed a new release with the corrected code. You can reinstall it from pip. It should work for you now.
