### ISSUE TITLE
Image too large. How suppress drawing when using pyWGCNA_obj.preprocess() ?

### ISSUE THREAD

**Issue by yizhang-zoey** [mortazavilab/PyWGCNA#84]
I am using pyWGCNA on a large data `pyWGCNA_obj` .

```
 AnnData object with n_obs × n_vars = 11963 × 28991
```
There is an `Error` when I use `pyWGCNA_obj.preprocess()` .
```
Image size of 85900x1000 pixels is too large. It must be less than 2^16 in each direction.
<Figure size 85900x1000 with 0 Axes>
```
How can I suppress drawing the hierarchical clustering plot when using `pyWGCNA_obj.preprocess()` to resolve the issue?

**Comment by nargesr** [comment]
Hi,

right now, I don't have any parameters to suppress drawing. you can put save to False to avoid saving but it will draw it anyway so I assume it's not gonna solve your problem. 
I'll add another parameter for this in the next few days but just make sure you don't have any outliers.

**Comment by nargesr** [comment]
Hi @yizhang-zoey 

I added an option (`show`) to suppress the drawing. Hopefully, that will fix your problem
more info in [API doc](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=preproce#PyWGCNA.wgcna.WGCNA.preprocess).

**Comment by yizhang-zoey** [comment]
> Hi @yizhang-zoey
> 
> I added an option (`show`) to suppress the drawing in v2.0.1. Hopefully, that will fix your problem more info in [API doc](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=preproce#PyWGCNA.wgcna.WGCNA.preprocess).

Thanks, it has been fixed!
