### ISSUE TITLE
error experienced in tutorial

### ISSUE THREAD

**Issue by chakitarora** [mortazavilab/PyWGCNA#89]
Hi, 

i was following the quick_tutorial (5xFAD_paper) to understand the basic pipeline before using it onto my project and i get this error when i execute 'pyWGCNA_5xFAD.findModules()'
<img width="863" alt="Screenshot 2024-02-09 at 16 13 22" src="https://github.com/mortazavilab/PyWGCNA/assets/32720238/87ada2d1-9d96-4968-8121-6e60d9478fb3">
. Can you help me with this? Thanks.

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 pyWGCNA_5xFAD.findModules()

File ~/.conda/envs/Py3.10/lib/python3.10/site-packages/PyWGCNA/wgcna.py:300, in WGCNA.findModules(self, **kwargs)
    297 self.datExpr.var['dynamicColors'] = WGCNA.labels2colors(labels=dynamicMods)
    299 # Calculate eigengenes
--> 300 MEList = WGCNA.moduleEigengenes(expr=self.datExpr.to_df(), colors=self.datExpr.var['dynamicColors'])
    302 self.MEs = MEList['eigengenes']
    303 if 'MEgrey' in self.MEs.columns:

File ~/.conda/envs/Py3.10/lib/python3.10/site-packages/PyWGCNA/wgcna.py:2036, in WGCNA.moduleEigengenes(expr, colors, impute, nPC, align, excludeGrey, grey, subHubs, softPower, scaleVar, trapErrors)
   2034 if not check:
   2035     if not trapErrors:
-> 2036         sys.exit("Error!")
   2037     print(" ..ME calculation of module", modulename, "failed with the following error:", flush=True)
   2038     print("     ", pc, " ..the offending module has been removed.", flush=True)

SystemExit: Error!

**Comment by chakitarora** [comment]
Installed dependencies:
  
  pandas>=1.4.4
  numpy==1.23.2
  scipy>=1.9.1
  scikit-learn>=1.2.2
  statsmodels>=0.13.5
  matplotlib>=3.5.2
  seaborn>=0.11.2
  biomart>=0.9.2
  gseapy>=1.0.1
  pyvis>=0.3.1
  setuptools>=67.4.0
  reactome2py>=3.0.0
  anndata>=0.8.0
  requests>=2.28.1
  networkx>=2.8.4
  rsrc>=0.1.3
  psutil>=5.9.0

**Comment by chakitarora** [comment]
Dependencies of PyWGCNA:

Required	|	Installed

pandas>=1.4.4	|	2.0.3
numpy==1.23.2	|	1.23.2
scipy>=1.9.1	|	1.11.1
scikit-learn>=1.2.2	|	1.3.0
statsmodels>=0.13.5	|	0.14.0
matplotlib>=3.5.2	|	3.5.2
seaborn>=0.11.2	|	0.12.2
biomart>=0.9.2	|	0.9.2
gseapy>=1.0.1	|	1.0.5
pyvis>=0.3.1	|	0.3.2
setuptools>=67.4.0	|	68.0.0
reactome2py>=3.0.0	|	3.0.0
anndata>=0.8.0	|	0.9.2
requests>=2.28.1	|	2.31.0
networkx>=2.8.4	|	3.1
rsrc>=0.1.3	|	0.1.3
psutil>=5.9.0	|	5.9.1

**Comment by nargesr** [comment]
Hi, 

not sure what’s your problem but which version of PyWGCNA do you have? which version of Python do you have?
if your PyWGCNA is any version >= 2.0.0, you should have pandas >= 2.0.0

I also updated [requirements.txt](https://github.com/mortazavilab/PyWGCNA/blob/main/requirements.txt), so you can check the version of the packages I have.

I would also make sure I use the latest version of the tutorial and data. 
I would also try making a new environment and doing a fresh install.

**Comment by chakitarora** [comment]
I have this:

Python 3.9.0
PyWGCNA 1.16.8
pandas 2.0.3

and i am following the latest github tutorial and data (as linked in the .ipynb)

**Comment by nargesr** [comment]
if you look at the [release log](https://github.com/mortazavilab/PyWGCNA/releases) you can find out that even though the version of PyWGCNA ==1.16.8 is stable but is not the latest version and it’s not compatible with pandas >= 2.x.x
Also if you look at [here](https://github.com/mortazavilab/PyWGCNA#installation), you can find out that I have Python 3.10 so not sure if Python 3.9 is the problem or not

First, I would try to update pyWGCNA and double-check the version of packages with [requirements.txt](https://github.com/mortazavilab/PyWGCNA/blob/main/requirements.txt) and then if you still have the problem, I would try updating python

**Comment by chakitarora** [comment]
Thanks for the support. Let me follow the steps you suggested and then see if this issue is resolved.

**Comment by chakitarora** [comment]
Updated PyWGCNA to 2.0.3. Now it works fine. Thanks!
