### ISSUE TITLE
Module Colors

### ISSUE THREAD

**Issue by nmank** [mortazavilab/PyWGCNA#9]
Hi,

Thanks for your fix for the last bug!

I think I found another one in version 1.0.0

When I run findModules, I get the error that "Gray" isn't in colorSeq.

I think you can fix this by just removing line 1822 in wgcna.py that says:
                  colorSeq.remove("Gray")

Thanks,
Nate

**Comment by nargesr** [comment]
Hi, it should be fixed by now.
I removed that specific color to avoid confusion between the "grey" module in the original WGCNA and "gray".
