### ISSUE TITLE
a issue for findModules()

### ISSUE THREAD

**Issue by songbowen1995** [mortazavilab/PyWGCNA#93]
AttributeError: 'DataFrame' object has no attribute 'Value'. Did you mean: 'values'?

**Comment by nargesr** [comment]
Hi @songbowen1995 

I need more information to be able to help you with the error you got. 
Can you send me full error? Also which function did give you this error?

**Comment by songbowen1995** [comment]
Thanks @nargesr 
I have resolved this issue and thank you very much for your reply. The reason for the error is related to my gene expression matrix. I used TMT mass spectrometry data for protein abundance, but did not normalize it. Additionally, as a test, the protein I inserted was too small, which caused this error to occur. The problem has been resolved so far. Thank you very much.

**Comment by nargesr** [comment]
that's great! I'm going to close this issue then. 
but in the future, If you face any errors, please include the full error along with the command you used. Thank you so much
