### ISSUE TITLE
findModules() inappropriately passes all kwargs to pickSoftThreshold() and cuttreeHybrid()

### ISSUE THREAD

**Issue by JShermanK1** [mortazavilab/PyWGCNA#94]
Thanks for all the work. 

I'm trying to do findModules(deepSplit= 0) to get cuttreeHybrid(deepSplit= 0), but deepSplit is being passed to pickSoftThreshold() which results in `got an unexpected keyword argument 'deepSplit'` . Maybe take the user provided kwargs and only fill in the unspecified keys with default values, then you can parcel out kwargs to the appropriate function calls?

As a sidenote, the API documentation states that deepSplit defaults to 1, but when I dig into the code it appears that it is actually 2.

I am ultimately trying to see if broader clusters result in better gene set enrichment. Am I going about this in a naive manner?

**Comment by nargesr** [comment]
Hi @JShermanK1 , Sorry for the delay!
I just released the new version which hopefully solves your problem

`findModules()` is more like a wrapper function so I ended up changing the input a little bit. 
please look at the [API documentation](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=findm#PyWGCNA.wgcna.WGCNA.findModules) and let me know if you have any problems/questions.
