### ISSUE TITLE
Re-naming modules

### ISSUE THREAD

**Issue by NezaCankar** [mortazavilab/PyWGCNA#95]
Hi, Narges

Error 1-
 When running .analyseWGCNA, the code automatically assigns modules called “dimgrey”, “lightgrey”, “darkgrey” etc. My attempt was to manually change those. However, after changing columns "moduleColors" and "dynamicColors", in "pyWGCNA_dataframe.datExpr.var" and running pyWGCNA_dataframe.analyseWGCNA, there is a following error:

<img width="1018" alt="Error 1" src="https://github.com/mortazavilab/PyWGCNA/assets/159801990/0665c333-80e8-4b3b-9cea-845a2ef959a5">

Few more questions:
Q1: When doing functional enrichments (EnrichR), what is a current setting for considering background gene/protein list? If whole genome, would it be possible to consider custom background (eg. all detected genes/proteins in a specific dataset)?
Q2: Is it possible to extract the p-value (significance) for specific module (eg. to see which module is the most significant compared to the rest)?
Q3: Is it possible to extract the Eigengene values for each of the detected modules?

Thanks so much!

Best, 
Neza

**Comment by nargesr** [comment]
Hi @NezaCankar 

According to the error, you need to also change the index in `self.datME`. 
I will try to add a change module color function in the next release but it will take some time so meanwhile you can try to change the color in `self.datME`.

about other questions:
Q1: Default is without any background but you can add your customer background.
please look at the [API documentation](https://mortazavilab.github.io/PyWGCNA/html/api.html?highlight=functional_enrichment_analysis#PyWGCNA.wgcna.WGCNA.functional_enrichment_analysis) and [GSEAPY package](https://gseapy.readthedocs.io/en/latest/gseapy_example.html#Enrichr-API) for more information about how you should pass your background.

Q2: I didn't get your question completely! based on what value do you want to compare your modules?

Q3: Yes! Eigengene values are stored in `self.datME`.
