### ISSUE TITLE
In the module Network Plot, Can we label the node as gene_name instead of gene_id ?

### ISSUE THREAD

**Issue by davidbinod** [mortazavilab/PyWGCNA#96]
Hello,
I was learning WGCNA with the PyWGCNA program.  It was easy to run.  Thank you for developing this program.  I have just an issue with a module Network Plot. In the network fig, It labeled  gene_id in the node, but I want to label it as gene_name. On clicking on the node, it shows the gene_name but I want to label the node with gene_name, not with gene_id. Would you please instruct me on how to do that?  I appreciate your help. 
Thanks,

**Comment by nargesr** [comment]
Hi,

Thank you for your kind comments.
If you initiate the PyWGCNA object with gene expression data in a way that indexes are gene names rather than gene IDs then it should show each node with the corresponding gene name (index).

Best,
Narges

**Comment by davidbinod** [comment]
Thank you for the reply. I will try and let you know.
binod
